In [4]:
import numpy as np

1D array- same as list but similar type of data.

In [21]:
arr1 =np.array([[2,3,4,5]])

In [22]:
print(arr1)


[[2 3 4 5]]


## 2D array

In [18]:
dp =np.array([[2,3,4,5],[2,3,4,56]])

In [26]:
print(dp*2)

[[  4   6   8  10]
 [  4   6   8 112]]


In [24]:
b=[1,2,3,4,5]
print(b*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [35]:
arr3 = np.array([
    [[2, 3, 4], [3, 4, 5]],
    [[6, 7, 8], [3, 4, 5]],
    [[6, 7, 8], [3, 4, 5]]
])

In [39]:
print(arr3)

[[[2 3 4]
  [3 4 5]]

 [[6 7 8]
  [3 4 5]]

 [[6 7 8]
  [3 4 5]]]


In [32]:
print(arr3.dtype)

int64


In [33]:
print(arr3.ndim)

3


In [37]:
print(arr3.shape)

(3, 2, 3)


In [38]:
print(arr3.size)

18


In [40]:
print(arr3.itemsize)

8


In [44]:
arr2=np.zeros((3,6))
print(arr2)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [45]:
arr2.dtype

dtype('float64')

In [46]:
arr5=np.ones((3,3))

In [47]:
arr5

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
arr6=np.full((4,4),6)

In [49]:
arr6

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [51]:
arr7=np.random.rand(10)
print(arr7)

[0.97398797 0.45564218 0.90666863 0.0036221  0.56747239 0.52843728
 0.06597087 0.85090509 0.72215062 0.16262688]


In [56]:
arr8=np.random.randn(3,4,5)
arr8

array([[[ 0.32288729,  0.20407591, -0.31315795,  0.76852271,
         -1.85131909],
        [-0.55196257, -1.60966035, -0.91751427,  0.50188   ,
          0.48446044],
        [-0.41071016,  0.91403185,  0.15348523,  1.81282738,
         -1.45780393],
        [ 2.01317106,  0.54306056, -2.58544281,  0.10331111,
          1.17891353]],

       [[-0.8116294 , -0.79565721,  1.03093209,  1.22822769,
          0.97429839],
        [ 1.12724832, -0.66279052, -0.30902867, -0.25597505,
          0.45120357],
        [-0.52364104, -0.67073125,  0.55430615,  0.52819295,
          0.39600497],
        [ 0.02703557,  0.7666379 ,  0.71765881,  0.8542881 ,
         -0.80224346]],

       [[-0.79387084, -0.05602873,  1.73958462,  0.27992844,
          1.04552107],
        [ 1.58427423,  0.39408694,  0.02589378,  0.31172384,
         -1.67353515],
        [-0.14617042, -0.49869125,  0.21184496, -1.33894739,
         -0.20152507],
        [ 1.01564299,  0.29884306, -1.25174794,  0.03677757,
         -1

In [104]:
arr9=np.random.randint(1,100,size=(3,4))

arr9

array([[83, 44, 71, 84],
       [42, 68, 81, 69],
       [92,  1, 18, 24]], dtype=int32)

In [107]:
arr10=np.arange(2,30,4)
arr10

array([ 2,  6, 10, 14, 18, 22, 26])